server:
  port: 8080
spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/bookmymovie
    driver-class-name: org.mariadb.jdbc.Driver
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MariaDB106Dialect
  cloud:
    function:
      definition: processBooking
    stream:
      bindings:
        sendPaymentReq-out-0:
          destination: send-payment-req
        processBooking-in-0:
          destination: process-booking-req
          group: ${spring.application.name}
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    connection-timeout: 10s
booking:
  ticket:
    url: http://localhost:8080/bookmymovie/api/booking/ticket
